name: Deploy Laravel App

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Known Hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy to Server using SSH
        id: deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ vars.SERVER_IP }} "
            cd /var/www/html/geezap && \
            git fetch origin main && \
            git reset --hard origin/main && \
            composer install --no-interaction --prefer-dist --optimize-autoloader && \
            php artisan migrate --force && \
            php artisan config:cache && \
            php artisan route:cache && \
            php artisan view:cache
          "

      - name: Send Discord Notification (Success)
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
          -d "{\"content\": \"✅ Deployment to production successful!\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}

      - name: Send Discord Notification (Failure)
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
          -d "{\"content\": \"❌ Deployment to production failed! Check GitHub Actions logs.\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}
