name: Geezap Deployment to Production Server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, bcmath, xml, curl, mysql, zip
          coverage: none

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install Composer Dependencies
        run: composer install --optimize-autoloader --no-dev --no-progress --no-interaction --prefer-dist

      - name: Cache NPM packages
        id: npm-cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install NPM Dependencies
        run: npm ci

      - name: Build NPM Assets
        run: npm run build

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: "."
          target: "/var/www/html/geezap"
          rm: true
          strip_components: 1

      - name: Run Remote Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          envs: DB_DATABASE,DB_USERNAME,DB_PASSWORD
          environment: |
            DB_DATABASE=${{ secrets.DB_DATABASE }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          script: |
            cd /var/www/html/geezap

            # Backup existing APP_KEY if .env exists
            if [ -f .env ]; then
              EXISTING_APP_KEY=$(grep APP_KEY .env | cut -d '=' -f2)
            fi

            # Create or update .env file
            cat > .env << EOL
            APP_NAME=Geezap
            APP_ENV=production
            APP_DEBUG=true
            APP_URL=http://160.191.163.6

            APP_LOCALE=en
            APP_FALLBACK_LOCALE=en
            APP_FAKER_LOCALE=en_US

            APP_MAINTENANCE_DRIVER=file
            APP_MAINTENANCE_STORE=database

            BCRYPT_ROUNDS=12

            LOG_CHANNEL=stack
            LOG_STACK=single
            LOG_DEPRECATIONS_CHANNEL=null
            LOG_LEVEL=debug

            DB_CONNECTION=mysql
            DB_HOST=127.0.0.1
            DB_PORT=3306
            DB_DATABASE=${DB_DATABASE}
            DB_USERNAME=${DB_USERNAME}
            DB_PASSWORD=${DB_PASSWORD}
            EOL

            # If we had an existing APP_KEY, restore it, otherwise generate new one
            if [ ! -z "$EXISTING_APP_KEY" ]; then
              sed -i "s|APP_KEY=|APP_KEY=$EXISTING_APP_KEY|" .env
            else
              php artisan key:generate --force
            fi

            # Install PHP MySQL if not installed
            sudo apt-get update
            sudo apt-get install -y php8.3-mysql

            # Restart PHP-FPM
            sudo systemctl restart php8.3-fpm

            # Put application in maintenance mode
            php artisan down --refresh=15

            # Clear all caches
            php artisan config:clear
            php artisan cache:clear
            php artisan view:clear
            php artisan route:clear

            # Update database
            php artisan migrate --force

            # Clear and cache config
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            # Install/update dependencies
            composer install --optimize-autoloader --no-dev --no-interaction

            # Set correct permissions
            sudo chown -R www-data:www-data .
            sudo find . -type f -exec chmod 644 {} \;
            sudo find . -type d -exec chmod 755 {} \;
            sudo chmod -R 775 storage bootstrap/cache

            # Restart queue workers
            php artisan queue:restart

            # Take application out of maintenance mode
            php artisan up

            # Optimize
            php artisan optimize
